config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'novels#index'
  resources :novels do
    resources :comments, :only => [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :novel
end

app/models/novel.rb
class Novel < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationControlle
  before_action :set_novel

  def create
    @comment = @novel.comments.create! comments_params
    @comment.update(:score => params[:score])
    redirect_to @novel
  end

  def destroy
    @post.comments.destroy params[:id]
    redirect_to @novel
  end

  private
    def set_novel
      @post = Novel.find(params[:novel_id])
    end

    def comments_params
      params.required(:comment).permit(:content)
    end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :set_novel, only: %i[ show edit update destroy ]

  # GET /novels or /novels.json
  def index
    @novels = Novel.all
  end

  # GET /novels/1 or /novels/1.json
  def show
  end

  # GET /novels/new
  def new
    @novel = Novel.new
  end

  # GET /novels/1/edit
  def edit
  end

  # POST /novels or /novels.json
  def create
    @novel = Novel.new(novel_params)

    respond_to do |format|
      if @novel.save
        format.html { redirect_to novel_url(@novel), notice: "Novel was successfully created." }
        format.json { render :show, status: :created, location: @novel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /novels/1 or /novels/1.json
  def update
    respond_to do |format|
      if @novel.update(novel_params)
        format.html { redirect_to novel_url(@novel), notice: "Novel was successfully updated." }
        format.json { render :show, status: :ok, location: @novel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /novels/1 or /novels/1.json
  def destroy
    @novel.destroy

    respond_to do |format|
      format.html { redirect_to novels_url, notice: "Novel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_novel
      @novel = Novel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def novel_params
      params.require(:novel).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/comments/_comment.html.erb
<p><%= tag.div('', class: 'score', data: {score: comment.score}) %></p>
<p><%= sanitize comment.content, tags: %w(h1 h2 h3 h4 h5 h6 ul ol li p a img table tr td em br strong div), attributes:  %w(id class href) %></p>
<p><%= link_to "Delete", "#{comment.novel_id}/comments/#{comment.id}", method: :delete, data: { confirm: 'Are you sure?' } %>

<script>
$(function() {
  $('.score').raty({
      readOnly: true,
      score: $('.score').data('score'),
      starType: 'i'
  })
})
</script

app/views/comments/_new.html.erb
<%= form_with(model: [ @novel, Comment.new ], remote: ture ) do |form| %>
  <div class="novel_rate"></div>
  Your Comment:<br>
  <%= form.hidden_field :content, id: :novel_comments %>
  <tirx-editor input="novel_comments"></trix-editor>
  <%= form.submit %>
<% end %>

<script>
$(function() {
    $('.novel_rate').raty({
      score: 5,
      starType: 'i',
    })
})
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Novel Post", root_path, class: "navbar-brand">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-expanded="/false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Menu
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to 'Novels', novels_path, class: "dropdown-item" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NovelPost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header'%>
   <div class="container">
    <%= yield %>
   </div>
  </body>
</html>

app/views/novels/_form.html.erb
<div data-controller="novel">
  <div class="form-left">
    <%= form_with(model: novel) do |form| %>
      <% if novel.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(novel.errors.count, "error") %> prohibited this novel from being saved:</h2>

          <ul>
            <% novel.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.hidden_field :content, id: :novel_content %>
    <%= trix-editor input="novel_content" 'data-target': 'novel.content', 'data-aciton': 'input->novel"content' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

  <div class="form-right">
    <h1>Content</h1>
    <div data-target="novel.preview"></div>
  </div>
</div>

<%= javascript_pack_tag 'application.js' %>

app/views/novels/edit.html.erb
<h1>Editing Novel</h1>

<%= render 'form', novel: @novel %>

<%= link_to 'Show', @novel %> |
<%= link_to 'Back', novels_path %>

app/views/novels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Novels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @novels.each do |novel| %>
      <tr>
        <td><%= novel.title %></td>
        <td><%= link_to 'Show', novel %></td>
        <td><%= link_to 'Edit', edit_novel_path(novel) %></td>
        <td><%= link_to 'Destroy', novel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Novel', new_novel_path %>

app/views/novels/new.html.erb
<% form_with(model: [ @novel, Comment.new ], remote: true) do |form| %>
  Your Comment:<br>
  <%= form.hidden_field :content, id: :novel_comments %>
  <trix-editor input="novel_comments"></trix-editor>
  <%= form.submit %>
<% end %>

app/views/novels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @novel.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= sanitize @novel.content, tags: %w(h1 h2 h3 h4 h5 h6 ul ol li p a img table tr td em br strong div), attributes: %w(id class href) %>
</p>

<h2>Comments</h2>
  <div id="comments">
    <%= render @novel.comments %>
  </div>
<%= render 'comments/new', novel: @novel


<%= link_to 'Edit', edit_novel_path(@novel) %> |
<%= link_to 'Back', novels_path %>